# this setup basically just lets us see writes working for manual verification
version: "3.8"
services:
  feeder:
    image: emojitracker/fakefeeder
    build: .
    links:
      - redis
    command: ["-target=redis://redis:6379", "-rate=150"]
  redis:
    image: redis:alpine
    ports:
        - "6379:6379"
